project:
  type: website
  output-dir: docs

website:
  title: "Foxmir Blog"
  site-url: 'https://foxmir.github.io/Foxmir-Blog/'
  google-analytics: 'G-VQW94RHSBY'
  search: false
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: life.qmd
        text: 'Life'
      - href: test4folder.qmd
        text: 'test4Folder'

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: false
    css: styles.css
    toc: false
