project:
  type: website
  output-dir: docs

website:
  title: "Foxmir Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: life.qmd
        text: 'Life'
      - href: test4folder.qmd
        text: 'test4Folder'

format:
  html:
    theme: Superhero
    css: styles.css
    toc: true
