project:
  type: website
  output-dir: docs

website:
  title: "Foxmir Blog"
  site-url: 'https://foxmir.github.io/Foxmir-Blog/'
  google-analytics: 'G-VQW94RHSBY'
  search: false
  navbar:
    left:
      - href: about.qmd
        text: About
    right:
      - href: articles.qmd
        text: 'Articles'
      - href: bits.qmd
        text: 'Bits'
      - href: learn.qmd
        text: 'Learn'
      - href: notes.qmd
        text: 'Notes'
      - href: reports.qmd
        text: 'Reports'

format:
  html:
    theme:
      light: flatly
      dark: darkly
    respect-user-color-scheme: false
    css: styles.css
    include-after-body: outline-sidebar.html
    toc: false
